# Generated by Django 4.1.7 on 2023-04-04 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('tag', models.CharField(max_length=8, verbose_name='Тэг')),
                ('description', models.CharField(default='-', max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'биржа',
                'verbose_name_plural': 'биржи',
            },
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Название')),
                ('description', models.CharField(default='-', max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип ценной бумаги',
                'verbose_name_plural': 'типы ценных бумаг',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='StockInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('tag', models.CharField(max_length=8, verbose_name='Тэг')),
                ('description', models.CharField(default='-', max_length=500, verbose_name='Описание')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.stockmarket', verbose_name='Биржа')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.stocktype', verbose_name='Тип бумаги')),
            ],
            options={
                'verbose_name': 'сводка по бумаге',
                'verbose_name_plural': 'сводки по бумагам',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('open', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Цена открытия')),
                ('high', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Максимальная цена')),
                ('low', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Минимальная цена')),
                ('close', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Цена закрытия')),
                ('volume', models.IntegerField(verbose_name='Объём продаж')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.stockinformation', verbose_name='Ценная бумага')),
            ],
            options={
                'verbose_name': 'ценная бумага',
                'verbose_name_plural': 'ценные бумаги',
            },
        ),
        migrations.CreateModel(
            name='CustomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.JSONField(verbose_name='Шаблон в формате JSON')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'шаблон',
                'verbose_name_plural': 'шаблоны',
            },
        ),
    ]
