# Generated by Django 4.1.7 on 2023-04-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtemplate',
            options={'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterModelOptions(
            name='stockinformation',
            options={'verbose_name': 'Сводка по бумаге', 'verbose_name_plural': 'Сводки по бумагам'},
        ),
        migrations.AlterModelOptions(
            name='stockmarket',
            options={'verbose_name': 'Биржа', 'verbose_name_plural': 'Биржи'},
        ),
        migrations.AlterModelOptions(
            name='stocktype',
            options={'verbose_name': 'Тип ценной бумаги', 'verbose_name_plural': 'Типы ценных бумаг'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stocktype',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stocktype',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
